### ISSUE TITLE
Modify Readme

### ISSUE THREAD

**Issue by anktrj** [houseofgeeks/visualrithms#10]
- Mention details for project setup for development.
 - Mention contributions guidelines
 - Mention appreciation to contributors

**Comment by ampsteric** [comment]
I would love to work on this. assign it to me please.

**Comment by ampsteric** [comment]
Also , is it eligible for the hacktober fest?

**Comment by anktrj** [comment]
Assigning this to you! @ampsteric 
As per I know every PR is eligible for Hacktoberfest until marked spam by the maintainer.

**Comment by ampsteric** [comment]
can you please give me links for a few contributors?

**Comment by anktrj** [comment]
Please refer this for contributors list! 
https://contributors-img.web.app/
This updates dynamically

**Comment by anktrj** [comment]
@EmperorYP7 Can you complete this?

**Comment by EmperorYP7** [comment]
Sure!
