### ISSUE TITLE
Landing Page is not responsive

### ISSUE THREAD

**Issue by tusharjain0022** [houseofgeeks/visualrithms#14]
### Description 
Landing Page doesn't seems to be responsive for different screen sizes.

### Concerning Folder 
* https://github.com/houseofgeeks/visualrithms/tree/master/src/Pages/Home
* https://github.com/houseofgeeks/visualrithms/tree/master/src/components/Navbar

### Screenshot

![Screenshot (465)](https://user-images.githubusercontent.com/59157988/95078185-5c1b8a00-0732-11eb-9773-0513b8046c6c.png)

**Comment by anktrj** [comment]
Labeled, thanks for reporting!

**Comment by pablowbk** [comment]
I can work on this one. 😁

**Comment by anktrj** [comment]
You can go for it @pablowbk
